"""Patch notebook cells 7.0 and 7.1 — fix backward compat + stderr capture."""
import json, sys

nb_path = 'd:/MADRLCitytleranflexresdr/CityLearn/examples/madrl_citylearn_v3_tutorial.ipynb'
nb = json.load(open(nb_path, encoding='utf-8'))

# ── new source for cell 7.0 (id=2adf11df) ────────────────────────────────────
# Key changes:
#   - run_cmd captures stderr and includes it in RuntimeError
#   - launcher_base_args() reads the launcher file to detect which optional
#     arguments are supported, keeping backward-compat with old CityLearn installs
new_src_70 = [
    "# ── 7.0  Helpers de ejecucion y monitor ─────────────────────────────────────────\n",
    "import subprocess, sys, os, json, re\n",
    "from pathlib import Path\n",
    "\n",
    "\n",
    "def run_cmd(cmd, *, cwd=REPO, check=True):\n",
    "    print('\\n' + '=' * 80)\n",
    "    print(' '.join(str(c) for c in cmd))\n",
    "    print('=' * 80)\n",
    "    sys.stdout.flush()\n",
    "    proc = subprocess.run(cmd, cwd=cwd, text=True, stderr=subprocess.PIPE)\n",
    "    # Mostrar stderr (errores argparse, trazas, advertencias) para que sea visible\n",
    "    if proc.stderr:\n",
    "        print(proc.stderr, end='', file=sys.stderr, flush=True)\n",
    "    if check and proc.returncode != 0:\n",
    "        stderr_snippet = (proc.stderr or '').strip()[-1500:]\n",
    "        msg = f'Comando fallo con exit={proc.returncode}'\n",
    "        if stderr_snippet:\n",
    "            msg += f'\\n--- stderr (ultimas 1500 chars) ---\\n{stderr_snippet}'\n",
    "        raise RuntimeError(msg)\n",
    "    return proc.returncode\n",
    "\n",
    "\n",
    "def _launcher_flags():\n",
    "    \"\"\"Lee el launcher y devuelve el conjunto de flags --foo registrados.\"\"\"\n",
    "    try:\n",
    "        src = Path(LAUNCHER).read_text(encoding='utf-8')\n",
    "        return set(re.findall(r'add_argument\\([\"\\'](-{1,2}[\\w-]+)[\"\\']', src))\n",
    "    except Exception:\n",
    "        return set()\n",
    "\n",
    "\n",
    "def launcher_base_args():\n",
    "    # Detectar capacidades del launcher para mantener compatibilidad hacia atras\n",
    "    # (el submodulo CityLearn en Colab puede ser mas antiguo que el notebook guardado).\n",
    "    _flags = _launcher_flags()\n",
    "\n",
    "    def _opt(flag, *values):\n",
    "        \"\"\"Añade [flag, *values] solo si el launcher registra ese flag.\"\"\"\n",
    "        return [flag, *values] if flag in _flags else []\n",
    "\n",
    "    # Todos los hiperparametros son explicitos aqui para maxima visibilidad y control.\n",
    "    # A100-SXM4-80GB: 73.6 GiB VRAM usable, 167 GiB RAM, 3 escenarios en paralelo.\n",
    "    base = [\n",
    "        PYTHON, '-B', LAUNCHER,\n",
    "        '--scenario', 'ALL',\n",
    "        '--seed', str(SEED),\n",
    "        '--episode-time-steps', str(EPISODE_STEPS),\n",
    "        '--episodes', str(EPISODES),\n",
    "        '--schema-path', SCHEMA_PATH,\n",
    "        '--output-root', OUTPUT_ROOT,\n",
    "        '--torch-threads', str(TORCH_THREADS),\n",
    "        '--live-progress-interval', str(LIVE_PROGRESS_INT),\n",
    "        '--live-heartbeat-seconds', str(LIVE_HEARTBEAT_SEC),\n",
    "        '--artifact-profile', ARTIFACT_PROFILE,\n",
    "        '--trace-record-interval', str(TRACE_INTERVAL),\n",
    "        '--trace-detail', TRACE_DETAIL,\n",
    "        '--gpu-profile', GPU_PROFILE,\n",
    "        '--cuda-memory-fraction', str(CUDA_MEMORY_FRACTION),\n",
    "        '--require-a100',\n",
    "        '--smoke-imports',\n",
    "        '--oom-retry',\n",
    "        '--live-monitor',\n",
    "        '--monitor-interval', '30',\n",
    "        # ── HAPPO ────────────────────────────────────────────────────────────────\n",
    "        '--happo-hidden-size', '1024',\n",
    "        # ── MASAC ────────────────────────────────────────────────────────────────\n",
    "        '--masac-critic-batch-size', '1024',\n",
    "        '--masac-buffer-size', '40',\n",
    "        '--masac-max-replay-buffer-gib', '40.0',\n",
    "        '--masac-rnn-hidden-dim', '1024',\n",
    "        '--masac-qmix-hidden-dim', '512',\n",
    "        '--masac-hyper-hidden-dim', '1024',\n",
    "        '--masac-preload-batch-device', 'cpu',\n",
    "        '--masac-actor-sample-times', '10',\n",
    "        '--masac-critic-train-steps', '2',\n",
    "        # ── MATD3 ────────────────────────────────────────────────────────────────\n",
    "        '--matd3-batch-size', '1024',\n",
    "        '--matd3-buffer-size', '2000000',\n",
    "        '--matd3-hidden-size', '1024',\n",
    "        '--matd3-train-interval', '100',\n",
    "        # ── MAAC ─────────────────────────────────────────────────────────────────\n",
    "        '--maac-batch-size', '1024',\n",
    "        '--maac-buffer-length', '1000000',\n",
    "        '--maac-hidden-size', '1024',\n",
    "        '--maac-steps-per-update', '100',\n",
    "        '--maac-num-updates', '16',\n",
    "    ]\n",
    "    # Argumentos opcionales segun version del launcher\n",
    "    # --parallel-scenarios: 3 escenarios concurrentes por algoritmo (A100-80GB)\n",
    "    base += _opt('--parallel-scenarios', '3')\n",
    "    return base\n",
    "\n",
    "\n",
    "def monitor_once():\n",
    "    return run_cmd([PYTHON, '-B', MONITOR, '--output-root', OUTPUT_ROOT, '--once', '--log-tail', '18'], check=False)\n",
]

# ── new source for cell 7.1 (id=3c0758f9) ────────────────────────────────────
new_src_71 = [
    "# ── 7.1  Preflight A100 + dry-run oficial ─────────────────────────────────────\n",
    "# 0. Verificar existencia de launcher y schema\n",
    "_launcher_path = Path(LAUNCHER)\n",
    "_schema_path   = Path(SCHEMA_PATH)\n",
    "if not _launcher_path.exists():\n",
    "    raise FileNotFoundError(\n",
    "        f'Launcher no encontrado: {LAUNCHER}\\n'\n",
    "        f'  → Vuelve a ejecutar la celda de clonado (1.2) para restaurar el submodulo CityLearn.'\n",
    "    )\n",
    "if not _schema_path.exists():\n",
    "    raise FileNotFoundError(\n",
    "        f'Schema no encontrado: {SCHEMA_PATH}\\n'\n",
    "        f'  → Genera el dataset Iquitos primero (celdas 3.x).'\n",
    "    )\n",
    "\n",
    "# 0b. Advertir si el launcher es de una version antigua (antes de parallel-scenarios)\n",
    "_flags = _launcher_flags()\n",
    "if '--parallel-scenarios' not in _flags:\n",
    "    print('\\n' + '!' * 72)\n",
    "    print('AVISO: El launcher en Colab es de una version antigua.')\n",
    "    print('  Los escenarios se ejecutaran en SECUENCIAL (3x mas lento en A100).')\n",
    "    print('  Para actualizar CityLearn y obtener ejecucion paralela:')\n",
    "    print('    1. En Colab: Runtime > Restart runtime')\n",
    "    print('    2. Vuelve a ejecutar desde la celda 1.2 (clonar repo)')\n",
    "    print('!' * 72 + '\\n')\n",
    "else:\n",
    "    print(f'Launcher : {LAUNCHER}  [parallel-scenarios=3 ✓]')\n",
    "print(f'Schema   : {SCHEMA_PATH}')\n",
    "\n",
    "# 1. Dry-run oficial: valida CUDA/A100, imports, rutas y 12 comandos planificados\n",
    "dry_run_cmd = launcher_base_args() + ['--dry-run', '--skip-completed']\n",
    "run_cmd(dry_run_cmd)\n",
    "monitor_once()\n",
    "\n",
    "# 2. Leer y validar status.json\n",
    "status_path = Path(OUTPUT_ROOT) / 'official_full_status.json'\n",
    "with open(status_path) as f:\n",
    "    status = json.load(f)\n",
    "assert status['status'] == 'dry_run', status['status']\n",
    "assert status['training_config']['a100_ready'] is True\n",
    "assert len(status['jobs']) == 12, len(status['jobs'])\n",
    "\n",
    "# 3. Verificar que cada output_dir es unico y esta dentro de OUTPUT_ROOT\n",
    "expected_root = Path(OUTPUT_ROOT).resolve()\n",
    "seen_outputs = set()\n",
    "for job in status['jobs']:\n",
    "    job_output = Path(job['output_dir'])\n",
    "    if not job_output.is_absolute():\n",
    "        job_output = Path(REPO) / job_output\n",
    "    job_output = job_output.resolve()\n",
    "    rel = job_output.relative_to(expected_root)\n",
    "    parts = rel.parts\n",
    "    assert len(parts) == 2, f'Layout inesperado: {job_output}'\n",
    "    assert parts[0] in ALGORITHMS, f'Algoritmo inesperado en output_dir: {parts[0]}'\n",
    "    assert parts[1] in {f'{sc}_seed_{SEED}' for sc in SCENARIOS}, f'Scenario/seed inesperado: {parts[1]}'\n",
    "    seen_outputs.add(str(job_output))\n",
    "assert len(seen_outputs) == 12, f'Output dirs duplicados o incompletos: {len(seen_outputs)}'\n",
    "\n",
    "print('Dry-run validado: 12 jobs planificados, A100 config lista, outputs aislados en OUTPUT_ROOT.')\n",
]

# Apply changes
changed = 0
for cell in nb['cells']:
    cid = cell.get('id', '')
    if cid == '2adf11df':
        cell['source'] = new_src_70
        cell['outputs'] = []
        cell['execution_count'] = None
        changed += 1
    elif cid == '3c0758f9':
        cell['source'] = new_src_71
        cell['outputs'] = []
        cell['execution_count'] = None
        changed += 1

print(f'Modified {changed} cells', file=sys.stderr)
json.dump(nb, open(nb_path, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('Saved OK', file=sys.stderr)
