"""Patch notebook cells 7.0 and 7.1 — auto-heal launcher backward compat."""
import json, sys

nb_path = 'd:/MADRLCitytleranflexresdr/CityLearn/examples/madrl_citylearn_v3_tutorial.ipynb'
nb = json.load(open(nb_path, encoding='utf-8'))

# ── new source for cell 7.0 (id=2adf11df) ────────────────────────────────────
new_src_70 = [
    "# ── 7.0  Helpers de ejecucion y monitor ─────────────────────────────────────────\n",
    "import subprocess, sys, os, json, re\n",
    "from pathlib import Path\n",
    "\n",
    "\n",
    "def run_cmd(cmd, *, cwd=REPO, check=True):\n",
    "    print('\\n' + '=' * 80)\n",
    "    print(' '.join(str(c) for c in cmd))\n",
    "    print('=' * 80)\n",
    "    sys.stdout.flush()\n",
    "    proc = subprocess.run(cmd, cwd=cwd, text=True, stderr=subprocess.PIPE)\n",
    "    if proc.stderr:\n",
    "        print(proc.stderr, end='', file=sys.stderr, flush=True)\n",
    "    if check and proc.returncode != 0:\n",
    "        stderr_snippet = (proc.stderr or '').strip()[-1500:]\n",
    "        msg = f'Comando fallo con exit={proc.returncode}'\n",
    "        if stderr_snippet:\n",
    "            msg += f'\\n--- stderr (ultimas 1500 chars) ---\\n{stderr_snippet}'\n",
    "        raise RuntimeError(msg)\n",
    "    return proc.returncode\n",
    "\n",
    "\n",
    "def _launcher_flags():\n",
    "    \"\"\"Devuelve el conjunto de flags --foo registrados en el launcher.\"\"\"\n",
    "    try:\n",
    "        src = Path(LAUNCHER).read_text(encoding='utf-8')\n",
    "        return set(re.findall(r'add_argument\\([\"\\'](-{1,2}[\\w-]+)[\"\\']', src))\n",
    "    except Exception:\n",
    "        return set()\n",
    "\n",
    "\n",
    "def _ensure_launcher_parallel():\n",
    "    \"\"\"Garantiza que el launcher soporta --parallel-scenarios.\n",
    "    1. Intenta git submodule update --remote CityLearn.\n",
    "    2. Si falla o no es suficiente, parchea el archivo del launcher en disco.\n",
    "    Devuelve True si el flag esta disponible despues del intento.\n",
    "    \"\"\"\n",
    "    if '--parallel-scenarios' in _launcher_flags():\n",
    "        return True  # ya soportado\n",
    "\n",
    "    print('\\n[launcher] --parallel-scenarios no encontrado. Intentando actualizar CityLearn...')\n",
    "\n",
    "    # Intento 1: git submodule update --remote CityLearn\n",
    "    r = subprocess.run(\n",
    "        ['git', 'submodule', 'update', '--init', '--remote', 'CityLearn'],\n",
    "        cwd=REPO, capture_output=True, text=True, timeout=120\n",
    "    )\n",
    "    if r.returncode == 0 and '--parallel-scenarios' in _launcher_flags():\n",
    "        print('[launcher] CityLearn actualizado via git — launcher ahora OK.')\n",
    "        return True\n",
    "    if r.returncode != 0:\n",
    "        print(f'[launcher] git submodule update devolvio exit={r.returncode}: {r.stderr.strip()[:200]}')\n",
    "\n",
    "    # Intento 2: patch en disco — insertar --parallel-scenarios tras --torch-threads\n",
    "    launcher_path = Path(LAUNCHER)\n",
    "    src = launcher_path.read_text(encoding='utf-8')\n",
    "    # Buscar la linea exacta de --torch-threads y añadir --parallel-scenarios tras ella\n",
    "    patched = re.sub(\n",
    "        r'([ \\t]+parser\\.add_argument\\(\"--torch-threads\"[^\\n]+\\n)',\n",
    "        r'\\1    parser.add_argument(\"--parallel-scenarios\", default=3, type=int,\\n'\n",
    "        r'                        help=\"Escenarios concurrentes por algoritmo (A100-80GB: 3).\")\\n',\n",
    "        src, count=1\n",
    "    )\n",
    "    if patched != src:\n",
    "        launcher_path.write_text(patched, encoding='utf-8')\n",
    "        print('[launcher] Launcher parcheado en disco con --parallel-scenarios=3.')\n",
    "        return '--parallel-scenarios' in _launcher_flags()\n",
    "\n",
    "    print('[launcher] No se pudo agregar --parallel-scenarios — se usara modo secuencial.')\n",
    "    return False\n",
    "\n",
    "\n",
    "def launcher_base_args():\n",
    "    # Todos los hiperparametros A100-SXM4-80GB explicitamente para maxima visibilidad.\n",
    "    _flags = _launcher_flags()\n",
    "\n",
    "    def _opt(flag, *values):\n",
    "        return [flag, *values] if flag in _flags else []\n",
    "\n",
    "    base = [\n",
    "        PYTHON, '-B', LAUNCHER,\n",
    "        '--scenario', 'ALL',\n",
    "        '--seed', str(SEED),\n",
    "        '--episode-time-steps', str(EPISODE_STEPS),\n",
    "        '--episodes', str(EPISODES),\n",
    "        '--schema-path', SCHEMA_PATH,\n",
    "        '--output-root', OUTPUT_ROOT,\n",
    "        '--torch-threads', str(TORCH_THREADS),\n",
    "        '--live-progress-interval', str(LIVE_PROGRESS_INT),\n",
    "        '--live-heartbeat-seconds', str(LIVE_HEARTBEAT_SEC),\n",
    "        '--artifact-profile', ARTIFACT_PROFILE,\n",
    "        '--trace-record-interval', str(TRACE_INTERVAL),\n",
    "        '--trace-detail', TRACE_DETAIL,\n",
    "        '--gpu-profile', GPU_PROFILE,\n",
    "        '--cuda-memory-fraction', str(CUDA_MEMORY_FRACTION),\n",
    "        '--require-a100',\n",
    "        '--smoke-imports',\n",
    "        '--oom-retry',\n",
    "        '--live-monitor',\n",
    "        '--monitor-interval', '30',\n",
    "        # ── HAPPO ─────────────────────────────────────────────────────────────\n",
    "        '--happo-hidden-size', '512',\n",
    "        # ── MASAC ─────────────────────────────────────────────────────────────\n",
    "        '--masac-critic-batch-size', '1024',\n",
    "        '--masac-buffer-size', '40',\n",
    "        '--masac-max-replay-buffer-gib', '40.0',\n",
    "        '--masac-rnn-hidden-dim', '1024',\n",
    "        '--masac-qmix-hidden-dim', '512',\n",
    "        '--masac-hyper-hidden-dim', '1024',\n",
    "        '--masac-preload-batch-device', 'cpu',\n",
    "        '--masac-actor-sample-times', '10',\n",
    "        '--masac-critic-train-steps', '2',\n",
    "        # ── MATD3 ─────────────────────────────────────────────────────────────\n",
    "        '--matd3-batch-size', '1024',\n",
    "        '--matd3-buffer-size', '2000000',\n",
    "        '--matd3-hidden-size', '1024',\n",
    "        '--matd3-train-interval', '100',\n",
    "        # ── MAAC ──────────────────────────────────────────────────────────────\n",
    "        '--maac-batch-size', '1024',\n",
    "        '--maac-buffer-length', '1000000',\n",
    "        '--maac-hidden-size', '1024',\n",
    "        '--maac-steps-per-update', '100',\n",
    "        '--maac-num-updates', '16',\n",
    "    ]\n",
    "    # --parallel-scenarios: 3 escenarios E1/E2/E3 concurrentes por algoritmo (A100-80GB)\n",
    "    base += _opt('--parallel-scenarios', '3')\n",
    "    return base\n",
    "\n",
    "\n",
    "def monitor_once():\n",
    "    return run_cmd([PYTHON, '-B', MONITOR, '--output-root', OUTPUT_ROOT, '--once', '--log-tail', '18'], check=False)\n",
]

# ── new source for cell 7.1 (id=3c0758f9) ────────────────────────────────────
new_src_71 = [
    "# ── 7.1  Preflight A100 + dry-run oficial ─────────────────────────────────────\n",
    "# 0. Verificar existencia de launcher y schema\n",
    "_launcher_path = Path(LAUNCHER)\n",
    "_schema_path   = Path(SCHEMA_PATH)\n",
    "if not _launcher_path.exists():\n",
    "    raise FileNotFoundError(\n",
    "        f'Launcher no encontrado: {LAUNCHER}\\n'\n",
    "        f'  → Vuelve a ejecutar la celda de clonado (1.2) para restaurar el submodulo CityLearn.'\n",
    "    )\n",
    "if not _schema_path.exists():\n",
    "    raise FileNotFoundError(\n",
    "        f'Schema no encontrado: {SCHEMA_PATH}\\n'\n",
    "        f'  → Genera el dataset Iquitos primero (celdas 3.x).'\n",
    "    )\n",
    "\n",
    "# 0b. Garantizar que el launcher soporta --parallel-scenarios (auto-cura)\n",
    "_parallel_ok = _ensure_launcher_parallel()\n",
    "if _parallel_ok:\n",
    "    print(f'Launcher : {LAUNCHER}  [parallel-scenarios=3 ✓]')\n",
    "else:\n",
    "    print(f'Launcher : {LAUNCHER}  [SECUENCIAL — sin --parallel-scenarios]')\n",
    "print(f'Schema   : {SCHEMA_PATH}')\n",
    "\n",
    "# 1. Dry-run oficial: valida CUDA/A100, imports, rutas y 12 comandos planificados\n",
    "dry_run_cmd = launcher_base_args() + ['--dry-run', '--skip-completed']\n",
    "run_cmd(dry_run_cmd)\n",
    "monitor_once()\n",
    "\n",
    "# 2. Leer y validar status.json\n",
    "status_path = Path(OUTPUT_ROOT) / 'official_full_status.json'\n",
    "with open(status_path) as f:\n",
    "    status = json.load(f)\n",
    "assert status['status'] == 'dry_run', status['status']\n",
    "assert status['training_config']['a100_ready'] is True\n",
    "assert len(status['jobs']) == 12, len(status['jobs'])\n",
    "\n",
    "# 3. Verificar que cada output_dir es unico y esta dentro de OUTPUT_ROOT\n",
    "expected_root = Path(OUTPUT_ROOT).resolve()\n",
    "seen_outputs = set()\n",
    "for job in status['jobs']:\n",
    "    job_output = Path(job['output_dir'])\n",
    "    if not job_output.is_absolute():\n",
    "        job_output = Path(REPO) / job_output\n",
    "    job_output = job_output.resolve()\n",
    "    rel = job_output.relative_to(expected_root)\n",
    "    parts = rel.parts\n",
    "    assert len(parts) == 2, f'Layout inesperado: {job_output}'\n",
    "    assert parts[0] in ALGORITHMS, f'Algoritmo inesperado en output_dir: {parts[0]}'\n",
    "    assert parts[1] in {f'{sc}_seed_{SEED}' for sc in SCENARIOS}, f'Scenario/seed inesperado: {parts[1]}'\n",
    "    seen_outputs.add(str(job_output))\n",
    "assert len(seen_outputs) == 12, f'Output dirs duplicados o incompletos: {len(seen_outputs)}'\n",
    "\n",
    "print('Dry-run validado: 12 jobs planificados, A100 config lista, outputs aislados en OUTPUT_ROOT.')\n",
    "if _parallel_ok:\n",
    "    print('Modo paralelo activo: HAPPO E1+E2+E3 correran simultaneamente (~30 h en A100).')\n",
    "else:\n",
    "    print('Modo SECUENCIAL activo: E1 → E2 → E3 por algoritmo (~90 h). Considera reiniciar runtime y reclonear.')\n",
]

# Apply changes
changed = 0
for cell in nb['cells']:
    cid = cell.get('id', '')
    if cid == '2adf11df':
        cell['source'] = new_src_70
        cell['outputs'] = []
        cell['execution_count'] = None
        changed += 1
    elif cid == '3c0758f9':
        cell['source'] = new_src_71
        cell['outputs'] = []
        cell['execution_count'] = None
        changed += 1

print(f'Modified {changed} cells', file=sys.stderr)
json.dump(nb, open(nb_path, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('Saved OK', file=sys.stderr)
