"""Patch notebook cell 7.0 — robust _ensure_launcher_parallel (checks _run_group too)."""
import json, sys

nb_path = 'd:/MADRLCitytleranflexresdr/CityLearn/examples/madrl_citylearn_v3_tutorial.ipynb'
nb = json.load(open(nb_path, encoding='utf-8'))

new_src_70 = [
    "# ── 7.0  Helpers de ejecucion y monitor ─────────────────────────────────────────\n",
    "import subprocess, sys, os, json, re\n",
    "from pathlib import Path\n",
    "\n",
    "\n",
    "def run_cmd(cmd, *, cwd=REPO, check=True):\n",
    "    print('\\n' + '=' * 80)\n",
    "    print(' '.join(str(c) for c in cmd))\n",
    "    print('=' * 80)\n",
    "    sys.stdout.flush()\n",
    "    proc = subprocess.run(cmd, cwd=cwd, text=True, stderr=subprocess.PIPE)\n",
    "    if proc.stderr:\n",
    "        print(proc.stderr, end='', file=sys.stderr, flush=True)\n",
    "    if check and proc.returncode != 0:\n",
    "        stderr_snippet = (proc.stderr or '').strip()[-1500:]\n",
    "        msg = f'Comando fallo con exit={proc.returncode}'\n",
    "        if stderr_snippet:\n",
    "            msg += f'\\n--- stderr (ultimas 1500 chars) ---\\n{stderr_snippet}'\n",
    "        raise RuntimeError(msg)\n",
    "    return proc.returncode\n",
    "\n",
    "\n",
    "def _launcher_flags():\n",
    "    \"\"\"Devuelve el conjunto de flags --foo registrados en el launcher.\"\"\"\n",
    "    try:\n",
    "        src = Path(LAUNCHER).read_text(encoding='utf-8')\n",
    "        return set(re.findall(r'add_argument\\([\"\\'](-{1,2}[\\w-]+)[\"\\']', src))\n",
    "    except Exception:\n",
    "        return set()\n",
    "\n",
    "\n",
    "def _launcher_is_full_parallel():\n",
    "    \"\"\"True solo si el launcher tiene TANTO el flag argparse COMO la logica de ejecucion\n",
    "    paralela (_run_group + ThreadPoolExecutor). Un patch parcial que solo agrego el flag\n",
    "    argparse corre HAPPO secuencialmente — devuelve False en ese caso.\n",
    "    \"\"\"\n",
    "    try:\n",
    "        src = Path(LAUNCHER).read_text(encoding='utf-8')\n",
    "        return (\n",
    "            '--parallel-scenarios' in src\n",
    "            and '_run_group' in src\n",
    "            and 'ThreadPoolExecutor' in src\n",
    "        )\n",
    "    except Exception:\n",
    "        return False\n",
    "\n",
    "\n",
    "def _ensure_launcher_parallel():\n",
    "    \"\"\"Garantiza que el launcher tiene TANTO el flag argparse COMO _run_group.\n",
    "\n",
    "    Un patch previo puede haber dejado solo el flag en argparse sin la logica de\n",
    "    ejecucion paralela — en ese caso _run_group no existe y HAPPO corre en serie.\n",
    "    Esta funcion detecta ese caso (solo flag, sin _run_group) y actualiza el launcher\n",
    "    desde el branch correcto.\n",
    "\n",
    "    Orden de intentos:\n",
    "      1. git fetch origin codex/iquitos-distillation-madrl-docs (branch con la fix)\n",
    "      2. git submodule update --init --remote CityLearn\n",
    "      3. git submodule update --init CityLearn (ref fija del padre)\n",
    "      4. patch de argparse en disco (degradado — SECUENCIAL, retorna False)\n",
    "    \"\"\"\n",
    "    if _launcher_is_full_parallel():\n",
    "        return True  # launcher completo — no hacer nada\n",
    "\n",
    "    src = Path(LAUNCHER).read_text(encoding='utf-8') if Path(LAUNCHER).exists() else ''\n",
    "    _has_flag = '--parallel-scenarios' in src\n",
    "    _has_exec = '_run_group' in src and 'ThreadPoolExecutor' in src\n",
    "    if _has_flag and not _has_exec:\n",
    "        print('\\n[launcher] ATENCION: launcher tiene --parallel-scenarios en argparse '\n",
    "              'pero le falta _run_group — ejecutaria en modo SECUENCIAL.')\n",
    "        print('[launcher] Actualizando al launcher completo...')\n",
    "    else:\n",
    "        print('\\n[launcher] --parallel-scenarios no disponible. Intentando actualizar...')\n",
    "\n",
    "    # Ruta del directorio CityLearn/\n",
    "    cl_dir = str(Path(LAUNCHER).parent.parent)\n",
    "    _CL_BRANCH = 'codex/iquitos-distillation-madrl-docs'\n",
    "\n",
    "    # ── Intento 1: git fetch origin <branch> + checkout del archivo del launcher ──\n",
    "    r_fetch = subprocess.run(\n",
    "        ['git', 'fetch', 'origin', _CL_BRANCH],\n",
    "        cwd=cl_dir, capture_output=True, text=True, timeout=90\n",
    "    )\n",
    "    if r_fetch.returncode == 0:\n",
    "        r_co = subprocess.run(\n",
    "            ['git', 'checkout', 'FETCH_HEAD', '--',\n",
    "             'scripts/colab_a100_official_launcher.py'],\n",
    "            cwd=cl_dir, capture_output=True, text=True, timeout=30\n",
    "        )\n",
    "        if r_co.returncode == 0 and _launcher_is_full_parallel():\n",
    "            print(f'[launcher] Launcher actualizado via git fetch {_CL_BRANCH} — paralelo OK.')\n",
    "            return True\n",
    "        if r_co.returncode != 0:\n",
    "            print(f'[launcher] git checkout fallo: {r_co.stderr.strip()[:200]}')\n",
    "    else:\n",
    "        print(f'[launcher] git fetch fallo (exit={r_fetch.returncode}): '\n",
    "              f'{r_fetch.stderr.strip()[:200]}')\n",
    "\n",
    "    # ── Intento 2: git submodule update --remote (sigue branch de .gitmodules) ──\n",
    "    r_rem = subprocess.run(\n",
    "        ['git', 'submodule', 'update', '--init', '--remote', 'CityLearn'],\n",
    "        cwd=REPO, capture_output=True, text=True, timeout=120\n",
    "    )\n",
    "    if r_rem.returncode == 0 and _launcher_is_full_parallel():\n",
    "        print('[launcher] CityLearn actualizado via submodule update --remote — paralelo OK.')\n",
    "        return True\n",
    "    if r_rem.returncode != 0:\n",
    "        print(f'[launcher] submodule update --remote exit={r_rem.returncode}: '\n",
    "              f'{r_rem.stderr.strip()[:200]}')\n",
    "\n",
    "    # ── Intento 3: submodule update sin --remote (ref fija del padre) ─────────\n",
    "    r_init = subprocess.run(\n",
    "        ['git', 'submodule', 'update', '--init', 'CityLearn'],\n",
    "        cwd=REPO, capture_output=True, text=True, timeout=120\n",
    "    )\n",
    "    if r_init.returncode == 0 and _launcher_is_full_parallel():\n",
    "        print('[launcher] CityLearn sincronizado via submodule update — paralelo OK.')\n",
    "        return True\n",
    "    if r_init.returncode != 0:\n",
    "        print(f'[launcher] submodule update exit={r_init.returncode}: '\n",
    "              f'{r_init.stderr.strip()[:200]}')\n",
    "\n",
    "    # ── Intento 4 (degradado): solo patch de argparse ─────────────────────────\n",
    "    launcher_path = Path(LAUNCHER)\n",
    "    src = launcher_path.read_text(encoding='utf-8')\n",
    "    if '--parallel-scenarios' not in src:\n",
    "        patched = re.sub(\n",
    "            r'([ \\t]+parser\\.add_argument\\(\"--torch-threads\"[^\\n]+\\n)',\n",
    "            r'\\1    parser.add_argument(\"--parallel-scenarios\", default=3, type=int,\\n'\n",
    "            r'                        help=\"Escenarios concurrentes por algoritmo.\")\\n',\n",
    "            src, count=1\n",
    "        )\n",
    "        if patched != src:\n",
    "            launcher_path.write_text(patched, encoding='utf-8')\n",
    "\n",
    "    print('[launcher] *** MODO DEGRADADO: solo argparse parcheado — falta _run_group. ***')\n",
    "    print('[launcher] *** HAPPO correra SECUENCIALMENTE (E1 → E2 → E3 ~33h).       ***')\n",
    "    print('[launcher] *** Para modo paralelo: reinicia el runtime y vuelve a clonar. ***')\n",
    "    return False\n",
    "\n",
    "\n",
    "def launcher_base_args():\n",
    "    # Todos los hiperparametros A100-SXM4-80GB explicitamente para maxima visibilidad.\n",
    "    _flags = _launcher_flags()\n",
    "\n",
    "    def _opt(flag, *values):\n",
    "        return [flag, *values] if flag in _flags else []\n",
    "\n",
    "    base = [\n",
    "        PYTHON, '-B', LAUNCHER,\n",
    "        '--scenario', 'ALL',\n",
    "        '--seed', str(SEED),\n",
    "        '--episode-time-steps', str(EPISODE_STEPS),\n",
    "        '--episodes', str(EPISODES),\n",
    "        '--schema-path', SCHEMA_PATH,\n",
    "        '--output-root', OUTPUT_ROOT,\n",
    "        '--torch-threads', str(TORCH_THREADS),\n",
    "        '--live-progress-interval', str(LIVE_PROGRESS_INT),\n",
    "        '--live-heartbeat-seconds', str(LIVE_HEARTBEAT_SEC),\n",
    "        '--artifact-profile', ARTIFACT_PROFILE,\n",
    "        '--trace-record-interval', str(TRACE_INTERVAL),\n",
    "        '--trace-detail', TRACE_DETAIL,\n",
    "        '--gpu-profile', GPU_PROFILE,\n",
    "        '--cuda-memory-fraction', str(CUDA_MEMORY_FRACTION),\n",
    "        '--require-a100',\n",
    "        '--smoke-imports',\n",
    "        '--oom-retry',\n",
    "        '--live-monitor',\n",
    "        '--monitor-interval', '30',\n",
    "        # ── HAPPO ─────────────────────────────────────────────────────────────\n",
    "        '--happo-hidden-size', '1024',\n",
    "        # ── MASAC ─────────────────────────────────────────────────────────────\n",
    "        '--masac-critic-batch-size', '1024',\n",
    "        '--masac-buffer-size', '40',\n",
    "        '--masac-max-replay-buffer-gib', '40.0',\n",
    "        '--masac-rnn-hidden-dim', '1024',\n",
    "        '--masac-qmix-hidden-dim', '512',\n",
    "        '--masac-hyper-hidden-dim', '1024',\n",
    "        '--masac-preload-batch-device', 'cpu',\n",
    "        '--masac-actor-sample-times', '10',\n",
    "        '--masac-critic-train-steps', '2',\n",
    "        # ── MATD3 ─────────────────────────────────────────────────────────────\n",
    "        '--matd3-batch-size', '1024',\n",
    "        '--matd3-buffer-size', '2000000',\n",
    "        '--matd3-hidden-size', '1024',\n",
    "        '--matd3-train-interval', '100',\n",
    "        # ── MAAC ──────────────────────────────────────────────────────────────\n",
    "        '--maac-batch-size', '1024',\n",
    "        '--maac-buffer-length', '1000000',\n",
    "        '--maac-hidden-size', '1024',\n",
    "        '--maac-steps-per-update', '100',\n",
    "        '--maac-num-updates', '16',\n",
    "    ]\n",
    "    base += _opt('--parallel-scenarios', '3')\n",
    "    return base\n",
    "\n",
    "\n",
    "def monitor_once():\n",
    "    return run_cmd([PYTHON, '-B', MONITOR, '--output-root', OUTPUT_ROOT, '--once', '--log-tail', '18'], check=False)\n",
]

changed = 0
for cell in nb['cells']:
    cid = cell.get('id', '')
    if cid == '2adf11df':
        cell['source'] = new_src_70
        cell['outputs'] = []
        cell['execution_count'] = None
        changed += 1

print(f'Modified {changed} cells', file=sys.stderr)
json.dump(nb, open(nb_path, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('Saved OK', file=sys.stderr)
